@startuml "Model"

entity User {

    + Id : int
    + Name : string
    + Email : string
    + Password : string
    + Files : File[3]
}

entity File {
    + Id : int
    + accountingAccounts : accountingAccount[]
}

entity accountingAccount {
        + AccountID : int
        + Entry : Entry[]
}

entity Entry {
    + EntryId : int
    + GegenKonto : accountingAccount
    + Haben : decimal
    + Soll : decimal
    + Datum : DateTime
}

User o--> File 

File o--> accountingAccount 

accountingAccount o--> Entry 

@enduml